import type { Express } from 'express';

import resourcesRouter from '../routes/resources';
import calendarRouter from '../routes/calendar';
import eventsRouter from '../routes/events';
import authRouter from '../routes/auth';
import hubspotRouter from '../routes/hubspot';
import hubspotDealsRouter from '../routes/hubspotDeals';
import membersRouter from '../routes/members';
import usersRouter from '../routes/users';
import wellnessRouter from '../routes/wellness';
import guestPassesRouter from '../routes/guestPasses';
import passesRouter from '../routes/passes';
import baysRouter from '../routes/bays';
import notificationsRouter from '../routes/notifications';
import pushRouter from '../routes/push';
import availabilityRouter from '../routes/availability';
import cafeRouter from '../routes/cafe';
import galleryRouter from '../routes/gallery';
import announcementsRouter from '../routes/announcements';
import faqsRouter from '../routes/faqs';
import inquiriesRouter from '../routes/inquiries';
import imageUploadRouter from '../routes/imageUpload';
import closuresRouter from '../routes/closures';
import membershipTiersRouter from '../routes/membershipTiers';
import trainingRouter from '../routes/training';
import toursRouter from '../routes/tours';
import bugReportsRouter from '../routes/bugReports';
import trackmanRouter from '../routes/trackman';
import noticesRouter from '../routes/notices';
import testAuthRouter from '../routes/testAuth';
import rosterRouter from '../routes/roster';
import staffCheckinRouter from '../routes/staffCheckin';
import dataIntegrityRouter from '../routes/dataIntegrity';
import dataToolsRouter from '../routes/dataTools';
import legacyPurchasesRouter from '../routes/legacyPurchases';
import mindbodyRouter from '../routes/mindbody';
import settingsRouter from '../routes/settings';
import stripeRouter from '../routes/stripe';
import waiversRouter from '../routes/waivers';
import groupBillingRouter from '../routes/groupBilling';
import memberBillingRouter from '../routes/memberBilling';
import myBillingRouter from '../routes/myBilling';
import checkoutRouter from '../routes/checkout';
import dayPassesRouter from '../routes/dayPasses';
import financialsRouter from '../routes/financials';
import accountRouter from '../routes/account';
import dataExportRouter from '../routes/dataExport';
import staffManualBookingRouter from '../routes/staff/manualBooking';
import staffRouter from '../routes/staff';
import tierFeaturesRouter from '../routes/tierFeatures';
import resendWebhooksRouter from '../routes/resendWebhooks';
import conferencePrepaymentRouter from '../routes/conference/prepayment';
import pricingRouter from '../routes/pricing';
import authGoogleRouter from '../routes/auth-google';
import idScannerRouter from '../routes/idScanner';
import emailTemplatesRouter from '../routes/emailTemplates';
import monitoringRouter from '../routes/monitoring';
import { registerObjectStorageRoutes } from '../replit_integrations/object_storage';

export function registerRoutes(app: Express): void {
  app.use(resourcesRouter);
  app.use(calendarRouter);
  app.use(eventsRouter);
  app.use(authRouter);
  app.use(authGoogleRouter);
  app.use('/api/auth', testAuthRouter);
  app.use(hubspotRouter);
  app.use(hubspotDealsRouter);
  app.use(accountRouter);
  app.use(dataExportRouter);
  app.use(membersRouter);
  app.use(usersRouter);
  app.use(wellnessRouter);
  app.use(guestPassesRouter);
  app.use(passesRouter);
  app.use(baysRouter);
  app.use(notificationsRouter);
  app.use(pushRouter);
  app.use(availabilityRouter);
  app.use(cafeRouter);
  app.use(galleryRouter);
  app.use(announcementsRouter);
  app.use(faqsRouter);
  app.use(inquiriesRouter);
  app.use(imageUploadRouter);
  app.use(closuresRouter);
  app.use(membershipTiersRouter);
  app.use(trainingRouter);
  app.use(toursRouter);
  app.use(bugReportsRouter);
  app.use(trackmanRouter);
  app.use(noticesRouter);
  app.use(rosterRouter);
  app.use(staffCheckinRouter);
  app.use(dataIntegrityRouter);
  app.use(dataToolsRouter);
  app.use(legacyPurchasesRouter);
  app.use(mindbodyRouter);
  app.use(settingsRouter);
  app.use(stripeRouter);
  app.use(waiversRouter);
  app.use(groupBillingRouter);
  app.use(memberBillingRouter);
  app.use(myBillingRouter);
  app.use(checkoutRouter);
  app.use(dayPassesRouter);
  app.use(financialsRouter);
  app.use(staffManualBookingRouter);
  app.use(staffRouter);
  app.use(tierFeaturesRouter);
  app.use(resendWebhooksRouter);
  app.use(conferencePrepaymentRouter);
  app.use(pricingRouter);
  app.use(idScannerRouter);
  app.use(emailTemplatesRouter);
  app.use(monitoringRouter);
  registerObjectStorageRoutes(app);
}
