-- ============================================================================
-- NO-OP MIGRATION
-- ============================================================================
-- FK constraints for booking_requests, booking_participants, wellness_enrollments,
-- booking_fee_snapshots, guest_pass_holds, conference_prepayments, and
-- booking_wallet_passes are managed at runtime by db-init.ts (not Drizzle schema)
-- to avoid deployment migration failures caused by orphaned production data.
--
-- The .references() declarations were removed from the Drizzle schema so the
-- deployment system does not auto-generate ALTER TABLE statements that fail
-- on orphaned data. db-init.ts cleans up orphans first, then adds the FK
-- constraints at app startup.
-- ============================================================================
SELECT 1;
