import { startIntegrityScheduler } from './integrityScheduler';
import { startWaiverReviewScheduler } from './waiverReviewScheduler';
import { startStripeReconciliationScheduler } from './stripeReconciliationScheduler';
import { startFeeSnapshotReconciliationScheduler } from './feeSnapshotReconciliationScheduler';
import { startGracePeriodScheduler } from './gracePeriodScheduler';
import { startBookingExpiryScheduler } from './bookingExpiryScheduler';
import { startBackgroundSyncScheduler } from './backgroundSyncScheduler';
import { startDailyReminderScheduler } from './dailyReminderScheduler';
import { startMorningClosureScheduler } from './morningClosureScheduler';
import { startWeeklyCleanupScheduler } from './weeklyCleanupScheduler';
import { startInviteExpiryScheduler } from './inviteExpiryScheduler';
import { startCommunicationLogsScheduler } from './communicationLogsScheduler';
import { startWebhookLogCleanupScheduler } from './webhookLogCleanupScheduler';
import { startHubSpotQueueScheduler } from './hubspotQueueScheduler';
import { startHubSpotFormSyncScheduler } from './hubspotFormSyncScheduler';
import { startSessionCleanupScheduler } from './sessionCleanupScheduler';
import { startUnresolvedTrackmanScheduler } from './unresolvedTrackmanScheduler';
import { startGuestPassResetScheduler } from './guestPassResetScheduler';
import { startMemberSyncScheduler } from './memberSyncScheduler';
import { startDuplicateCleanupScheduler } from './duplicateCleanupScheduler';
import { startRelocationCleanupScheduler } from './relocationCleanupScheduler';
import { startStuckCancellationScheduler } from './stuckCancellationScheduler';
import { startPendingUserCleanupScheduler } from './pendingUserCleanupScheduler';
import { startWebhookEventCleanupScheduler } from './webhookEventCleanupScheduler';
import { startJobProcessor, stopJobProcessor } from '../core/jobQueue';
import { schedulerTracker } from '../core/schedulerTracker';

export function initSchedulers(): void {
  schedulerTracker.registerScheduler('Background Sync', 5 * 60 * 1000);
  schedulerTracker.registerScheduler('Daily Reminder', 30 * 60 * 1000);
  schedulerTracker.registerScheduler('Morning Closure', 30 * 60 * 1000);
  schedulerTracker.registerScheduler('Weekly Cleanup', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Invite Expiry', 5 * 60 * 1000);
  schedulerTracker.registerScheduler('Integrity Check', 30 * 60 * 1000);
  schedulerTracker.registerScheduler('Auto-Fix Tiers', 4 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Abandoned Pending Cleanup', 6 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Waiver Review', 4 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Stripe Reconciliation', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Fee Snapshot Reconciliation', 15 * 60 * 1000);
  schedulerTracker.registerScheduler('Grace Period', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Booking Expiry', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Communication Logs Sync', 30 * 60 * 1000);
  schedulerTracker.registerScheduler('Webhook Log Cleanup', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Session Cleanup', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Unresolved Trackman', 15 * 60 * 1000);
  schedulerTracker.registerScheduler('HubSpot Queue', 2 * 60 * 1000);
  schedulerTracker.registerScheduler('HubSpot Form Sync', 30 * 60 * 1000);
  schedulerTracker.registerScheduler('Member Sync', 24 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Duplicate Cleanup', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Guest Pass Reset', 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Relocation Cleanup', 5 * 60 * 1000);
  schedulerTracker.registerScheduler('Stuck Cancellation', 2 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Pending User Cleanup', 6 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Webhook Event Cleanup', 24 * 60 * 60 * 1000);
  schedulerTracker.registerScheduler('Job Queue Processor', 5000);

  startBackgroundSyncScheduler();
  startDailyReminderScheduler();
  startMorningClosureScheduler();
  startWeeklyCleanupScheduler();
  startInviteExpiryScheduler();
  startIntegrityScheduler();
  startWaiverReviewScheduler();
  startStripeReconciliationScheduler();
  startFeeSnapshotReconciliationScheduler();
  startGracePeriodScheduler();
  startBookingExpiryScheduler();
  startCommunicationLogsScheduler();
  startWebhookLogCleanupScheduler();
  startSessionCleanupScheduler();
  startUnresolvedTrackmanScheduler();
  startHubSpotQueueScheduler();
  startHubSpotFormSyncScheduler();
  startMemberSyncScheduler();
  startDuplicateCleanupScheduler();
  startGuestPassResetScheduler();
  startRelocationCleanupScheduler();
  startStuckCancellationScheduler();
  startPendingUserCleanupScheduler();
  startWebhookEventCleanupScheduler();
  startJobProcessor(5000);
}

export function stopSchedulers(): void {
  stopJobProcessor();
}
